/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <string.h>
#include "fileOp.h"

int getToken(char* token);

int* escribir_1_svc(write_parameters *argp, struct svc_req *rqstp){
	static int  result;

	printf("escribir() is called with token: %s and content: %s \n",argp->token,argp->contenido);

	//validar el token
	char local_token[32] = {" "};
	getToken(local_token);

	if(strcmp(local_token,argp->token)==0){
		printf("token valido receiv \n");
	}else{
		printf("token invalido \n");
	}
	
	
	//////////////////////&&&&&&&&
	//escribir el archivo y retornar un exit_sucsess or exit_failure. y termino todo
	return &result;
}

int getToken(char* token){
    FILE *file = fopen("token.txt", "r");
    
    if (file == NULL) {
        perror("Error al abrir el archivo");
        return 1;
    }

    char buffer[32] = {" "};

    fgets(buffer,sizeof(buffer), file);

    fclose(file);

    strcpy(token,buffer);

    return EXIT_SUCCESS;
}
