/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fileOp.h"

bool_t
xdr_write_parameters (XDR *xdrs, write_parameters *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->token, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->contenido, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
